name: Generate and Deploy HexDocs

on:
  push:
    branches:
      - elixir/genservers  # or your default branch

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.15'  # your Elixir version
        otp-version: '26'       # your OTP version

    - name: Install dependencies
      run: mix deps.get

    - name: Build HexDocs
      run: mix docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc