name: Generate and Deploy HexDocs

on:
  push:
    branches:
      - main
      - elixir/**

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.18'
        otp-version: '27'

    - name: Install dependencies
      working-directory: elixir
      run: mix deps.get

    - name: Build HexDocs
      working-directory: elixir
      run: mix docs

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./elixir/doc

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
