name: Generate and Deploy HexDocs

on:
  push:
    branches:
      - main
      - elixir/**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.18'
        otp-version: '27'

    - name: Install dependencies
      working-directory: elixir
      run: mix deps.get

    - name: Build HexDocs
      working-directory: elixir
      run: mix docs

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: ./elixir/doc
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
