name: Tests

on:
  push

jobs:
  test-elixir:
    if: contains(github.ref, 'elixir')
    name: Test Elixir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-24.04]
        otp: [27.x]
        elixir: [1.18.3]
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        working-directory: elixir
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run tests
        working-directory: elixir
        run: |
          mix compile --force
          mix test

  test-python:
    if: contains(github.ref, 'python/')
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Run Python tests
        working-directory: python
        run: |
          python -m unittest discover